/* Generated from vim syntax file */
#include <stddef.h>
static const char *clipper_ctype[] = {
    "ANNOUNCE",
    "DECLARE",
    "EXIT",
    "EXTERNAL",
    "FIELD",
    "FUNCTION",
    "INIT",
    "LOCAL",
    "MEMVAR",
    "PARAMETERS",
    "PRIVATE",
    "PROCEDURE",
    "PUBLIC",
    "REQUEST",
    "STATIC",
    NULL
};

static const char *clipper_cstorageclass[] = {
    NULL
};

static const char *clipper_cstatement[] = {
    "ACCEPT",
    "ALL",
    "ALTERNATE",
    "APPEND",
    "AVERAGE",
    "BEGIN",
    "BELL",
    "BLANK",
    "BOX",
    "CALL",
    "CANCEL",
    "CENTURY",
    "CLEAR",
    "CLOSE",
    "COLOR",
    "COMMIT",
    "CONFIRM",
    "CONSOLE",
    "CONTINUE",
    "COPY",
    "COUNT",
    "CREATE",
    "CURSOR",
    "DATE",
    "DBEVALINFO",
    "DBFIELDINFO",
    "DBFILTERINFO",
    "DBFUNCTABLE",
    "DBLOCKINFO",
    "DBOPENINFO",
    "DBORDERCONDINFO",
    "DBORDERCREATEINF",
    "DBORDERINFO",
    "DBRELINFO",
    "DBSCOPEINFO",
    "DBSORTINFO",
    "DBSORTITEM",
    "DBTRANSINFO",
    "DBTRANSITEM",
    "DECIMALS",
    "DEFAULT",
    "DELETE",
    "DELETED",
    "DELIMITERS",
    "DEVICE",
    "DIR",
    "DISPLAY",
    "EJECT",
    "EPOCH",
    "ERASE",
    "ESCAPE",
    "EXACT",
    "EXCLUSIVE",
    "EXTE",
    "FILE",
    "FILTER",
    "FIND",
    "FIXED",
    "FORM",
    "FORMAT",
    "FROM",
    "FUNCTION",
    "GET",
    "GETS",
    "GO",
    "INDEX",
    "INPUT",
    "INTENSITY",
    "JOIN",
    "KEY",
    "KEYBOARD",
    "LABEL",
    "LIST",
    "LOCATE",
    "MARGIN",
    "MEMORY",
    "MENU",
    "MESSAGE",
    "NEW",
    "NIL",
    "NOTE",
    "ORDER",
    "PACK",
    "PATH",
    "PICT",
    "PRINTER",
    "PROCEDURE",
    "PROMPT",
    "QUIT",
    "READ",
    "RECALL",
    "REINDEX",
    "RELATION",
    "RELEASE",
    "RENAME",
    "REPLACE",
    "REPORT",
    "RESTORE",
    "RETURN",
    "RTLINKCMD",
    "RUN",
    "SAVE",
    "SAY",
    "SCOREBOARD",
    "SEEK",
    "SELECT",
    "SEQUENCE",
    "SET",
    "SHARED",
    "SKIP",
    "SOFTSEEK",
    "SORT",
    "STORE",
    "STRU",
    "STRUCTURE",
    "SUM",
    "TAG",
    "TEXT",
    "TMP",
    "TO",
    "TOTAL",
    "TYPE",
    "TYPEAHEAD",
    "UNIQUE",
    "UNLOCK",
    "UPDATE",
    "USE",
    "VALID",
    "WAIT",
    "WHEN",
    "WORKAREA",
    "WRAP",
    "ZAP",
    NULL
};

static const char *clipper_cconditional[] = {
    "CASE",
    "ELSE",
    "ENDCASE",
    "ENDIF",
    "IF",
    "IFDEF",
    "IFNDEF",
    "IIF",
    "OTHERWISE",
    NULL
};

static const char *clipper_crepeat[] = {
    "DO",
    "ENDDO",
    "FOR",
    "NEXT",
    "STEP",
    "TO",
    "WHILE",
    NULL
};

static const char *clipper_coperator[] = {
    NULL
};

static const char *clipper_cconstant[] = {
    NULL
};

static const char *clipper_ctypedef[] = {
    NULL
};

static const char *clipper_cstructure[] = {
    NULL
};

