/* Generated from vim syntax file */
#include <stddef.h>
static const char *i3config_ctype[] = {
    "contained",
    "container",
    "grow",
    "mark",
    "output",
    "scratchpad",
    "set",
    "shrink",
    "skipwhite",
    "window",
    "workspace",
    NULL
};

static const char *i3config_cstorageclass[] = {
    NULL
};

static const char *i3config_cstatement[] = {
    "append_layout",
    "bar",
    "bindcode",
    "bindsym",
    "border",
    "client",
    "contained",
    "default_border",
    "default_floating_border",
    "default_orientation",
    "exec",
    "exec_always",
    "exit",
    "floating",
    "floating_maximum_size",
    "floating_minimum_size",
    "focus",
    "focus_follows_mouse",
    "focus_on_window_activation",
    "focus_wrapping",
    "for_window",
    "force_display_urgency_hint",
    "force_xinerama",
    "fullscreen",
    "hide_edge_borders",
    "kill",
    "mark",
    "mode",
    "mouse_warping",
    "no_focus",
    "nop",
    "open",
    "popup_during_fullscreen",
    "reload",
    "rename",
    "resize",
    "restart",
    "scratchpad",
    "set",
    "show_marks",
    "skipwhite",
    "smart_borders",
    "smart_gaps",
    "split",
    "sticky",
    "swap",
    "tiling_drag",
    "title_align",
    "title_format",
    "title_window_icon",
    "unmark",
    "workspace",
    "workspace_auto_back_and_forth",
    "workspace_layout",
    NULL
};

static const char *i3config_cconditional[] = {
    "__focused__",
    "all",
    "class",
    "con_id",
    "con_mark",
    "contained",
    "floating",
    "floating_from",
    "id",
    "instance",
    "machine",
    "tiling",
    "tiling_from",
    "title",
    "urgent",
    "window_role",
    "window_type",
    "workspace",
    NULL
};

static const char *i3config_crepeat[] = {
    NULL
};

static const char *i3config_coperator[] = {
    "all",
    "always",
    "auto",
    "background",
    "binding_mode_indicator",
    "both",
    "bottom",
    "center",
    "child",
    "con_id",
    "contained",
    "container",
    "current",
    "default",
    "disable",
    "dock",
    "down",
    "enable",
    "floating",
    "focus",
    "focused",
    "focused_inactive",
    "focused_tab_title",
    "force",
    "hidden_state",
    "hide",
    "horizontal",
    "i3bar_command",
    "id",
    "ignore",
    "inverse_outer",
    "invisible",
    "key",
    "leave_fullscreen",
    "left",
    "minus",
    "mode",
    "mode_toggle",
    "modifier",
    "next",
    "no_gaps",
    "none",
    "nonprimary",
    "normal",
    "output",
    "padding",
    "parent",
    "pixel",
    "placeholder",
    "plus",
    "position",
    "prev",
    "primary",
    "restore",
    "right",
    "separator",
    "separator_symbol",
    "set",
    "show",
    "sibling",
    "skipwhite",
    "smart",
    "smart_no_gaps",
    "split",
    "splith",
    "splitv",
    "stacking",
    "status_command",
    "statusline",
    "strip_workspace_name",
    "strip_workspace_numbers",
    "tabbed",
    "tiling",
    "titlebar",
    "toggle",
    "top",
    "tray_output",
    "tray_padding",
    "unfocused",
    "up",
    "urgent",
    "vertical",
    "with",
    "workspace",
    "workspace_buttons",
    "workspace_command",
    "workspace_min_width",
    NULL
};

static const char *i3config_cconstant[] = {
    NULL
};

static const char *i3config_ctypedef[] = {
    NULL
};

static const char *i3config_cstructure[] = {
    NULL
};

